# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed May  8 23:19:16 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(875, 668)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.insTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insTable.sizePolicy().hasHeightForWidth())
        self.insTable.setSizePolicy(sizePolicy)
        self.insTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.insTable.setObjectName(_fromUtf8("insTable"))
        self.insTable.setColumnCount(6)
        self.insTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(5, item)
        self.insTable.horizontalHeader().setDefaultSectionSize(100)
        self.insTable.horizontalHeader().setMinimumSectionSize(56)
        self.insTable.verticalHeader().setDefaultSectionSize(30)
        self.insTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout.addWidget(self.insTable)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.rsTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsTable.sizePolicy().hasHeightForWidth())
        self.rsTable.setSizePolicy(sizePolicy)
        self.rsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.rsTable.setRowCount(5)
        self.rsTable.setObjectName(_fromUtf8("rsTable"))
        self.rsTable.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(5, item)
        self.rsTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_2.addWidget(self.rsTable)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.lsQueueTable = QtGui.QTableWidget(self.centralwidget)
        self.lsQueueTable.setRowCount(1)
        self.lsQueueTable.setObjectName(_fromUtf8("lsQueueTable"))
        self.lsQueueTable.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(5, item)
        self.lsQueueTable.verticalHeader().setVisible(False)
        self.lsQueueTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_2.addWidget(self.lsQueueTable)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.loadBufferTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBufferTable.sizePolicy().hasHeightForWidth())
        self.loadBufferTable.setSizePolicy(sizePolicy)
        self.loadBufferTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.loadBufferTable.setObjectName(_fromUtf8("loadBufferTable"))
        self.loadBufferTable.setColumnCount(3)
        self.loadBufferTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setHorizontalHeaderItem(2, item)
        self.loadBufferTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_4.addWidget(self.loadBufferTable)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.storeBufferTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storeBufferTable.sizePolicy().hasHeightForWidth())
        self.storeBufferTable.setSizePolicy(sizePolicy)
        self.storeBufferTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.storeBufferTable.setObjectName(_fromUtf8("storeBufferTable"))
        self.storeBufferTable.setColumnCount(3)
        self.storeBufferTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(2, item)
        self.storeBufferTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_4.addWidget(self.storeBufferTable)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.registerTable = QtGui.QTableWidget(self.centralwidget)
        self.registerTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.registerTable.setObjectName(_fromUtf8("registerTable"))
        self.registerTable.setColumnCount(11)
        self.registerTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(10, item)
        self.verticalLayout_3.addWidget(self.registerTable)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tumasulo算法演示平台", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Instructions:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Op", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Dest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Srci", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Srck", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Resvervation Stations:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Mult1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Mult2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Op", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vj", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vj", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vk", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Load/Store Queue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Load Buffer:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Store Buffer:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qi", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "F0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.registerTable.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))

