# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri May 10 10:50:06 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(892, 668)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.insTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insTable.sizePolicy().hasHeightForWidth())
        self.insTable.setSizePolicy(sizePolicy)
        self.insTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.insTable.setRowCount(0)
        self.insTable.setObjectName(_fromUtf8("insTable"))
        self.insTable.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.insTable.setHorizontalHeaderItem(6, item)
        self.insTable.horizontalHeader().setDefaultSectionSize(100)
        self.insTable.horizontalHeader().setMinimumSectionSize(56)
        self.insTable.verticalHeader().setDefaultSectionSize(30)
        self.insTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout.addWidget(self.insTable)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.rsTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsTable.sizePolicy().hasHeightForWidth())
        self.rsTable.setSizePolicy(sizePolicy)
        self.rsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.rsTable.setRowCount(5)
        self.rsTable.setObjectName(_fromUtf8("rsTable"))
        self.rsTable.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rsTable.setHorizontalHeaderItem(5, item)
        self.rsTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_2.addWidget(self.rsTable)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.lsQueueTable = QtGui.QTableWidget(self.centralwidget)
        self.lsQueueTable.setRowCount(1)
        self.lsQueueTable.setObjectName(_fromUtf8("lsQueueTable"))
        self.lsQueueTable.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.lsQueueTable.setHorizontalHeaderItem(5, item)
        self.lsQueueTable.verticalHeader().setVisible(False)
        self.lsQueueTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_2.addWidget(self.lsQueueTable)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.loadBufferTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBufferTable.sizePolicy().hasHeightForWidth())
        self.loadBufferTable.setSizePolicy(sizePolicy)
        self.loadBufferTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.loadBufferTable.setObjectName(_fromUtf8("loadBufferTable"))
        self.loadBufferTable.setColumnCount(2)
        self.loadBufferTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.loadBufferTable.setHorizontalHeaderItem(1, item)
        self.loadBufferTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_4.addWidget(self.loadBufferTable)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.storeBufferTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storeBufferTable.sizePolicy().hasHeightForWidth())
        self.storeBufferTable.setSizePolicy(sizePolicy)
        self.storeBufferTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.storeBufferTable.setObjectName(_fromUtf8("storeBufferTable"))
        self.storeBufferTable.setColumnCount(3)
        self.storeBufferTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.storeBufferTable.setHorizontalHeaderItem(2, item)
        self.storeBufferTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_4.addWidget(self.storeBufferTable)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/clock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(32, 32))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)
        self.lblClock = QtGui.QLabel(self.centralwidget)
        self.lblClock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClock.setObjectName(_fromUtf8("lblClock"))
        self.gridLayout.addWidget(self.lblClock, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.edtMemAddr = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMemAddr.sizePolicy().hasHeightForWidth())
        self.edtMemAddr.setSizePolicy(sizePolicy)
        self.edtMemAddr.setObjectName(_fromUtf8("edtMemAddr"))
        self.gridLayout.addWidget(self.edtMemAddr, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.edtMemValue = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMemValue.sizePolicy().hasHeightForWidth())
        self.edtMemValue.setSizePolicy(sizePolicy)
        self.edtMemValue.setObjectName(_fromUtf8("edtMemValue"))
        self.gridLayout.addWidget(self.edtMemValue, 2, 1, 1, 1)
        self.btnMemModify = QtGui.QPushButton(self.centralwidget)
        self.btnMemModify.setObjectName(_fromUtf8("btnMemModify"))
        self.gridLayout.addWidget(self.btnMemModify, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.memTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memTable.sizePolicy().hasHeightForWidth())
        self.memTable.setSizePolicy(sizePolicy)
        self.memTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.memTable.setObjectName(_fromUtf8("memTable"))
        self.memTable.setColumnCount(2)
        self.memTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.memTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.memTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.memTable)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.regTable = QtGui.QTableWidget(self.centralwidget)
        self.regTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.regTable.setObjectName(_fromUtf8("regTable"))
        self.regTable.setColumnCount(11)
        self.regTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.regTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.regTable.setHorizontalHeaderItem(10, item)
        self.regTable.verticalHeader().setMinimumSectionSize(15)
        self.verticalLayout_3.addWidget(self.regTable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actLoad = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actLoad.setIcon(icon1)
        self.actLoad.setObjectName(_fromUtf8("actLoad"))
        self.actEdit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEdit.setIcon(icon2)
        self.actEdit.setObjectName(_fromUtf8("actEdit"))
        self.actStep = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/step.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStep.setIcon(icon3)
        self.actStep.setObjectName(_fromUtf8("actStep"))
        self.actMultStep = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/mult_step.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMultStep.setIcon(icon4)
        self.actMultStep.setObjectName(_fromUtf8("actMultStep"))
        self.actRun = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRun.setIcon(icon5)
        self.actRun.setObjectName(_fromUtf8("actRun"))
        self.actMem = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/mem.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actMem.setIcon(icon6)
        self.actMem.setObjectName(_fromUtf8("actMem"))
        self.actRestart = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/restart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actRestart.setIcon(icon7)
        self.actRestart.setObjectName(_fromUtf8("actRestart"))
        self.actPause = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPause.setIcon(icon8)
        self.actPause.setObjectName(_fromUtf8("actPause"))
        self.menu.addAction(self.actLoad)
        self.menu.addAction(self.actEdit)
        self.menu_2.addAction(self.actStep)
        self.menu_2.addAction(self.actMultStep)
        self.menu_2.addAction(self.actPause)
        self.menu_2.addAction(self.actRun)
        self.menu_2.addAction(self.actRestart)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actLoad)
        self.toolBar.addAction(self.actEdit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actStep)
        self.toolBar.addAction(self.actMultStep)
        self.toolBar.addAction(self.actPause)
        self.toolBar.addAction(self.actRun)
        self.toolBar.addAction(self.actRestart)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edtMemAddr, self.edtMemValue)
        MainWindow.setTabOrder(self.edtMemValue, self.lsQueueTable)
        MainWindow.setTabOrder(self.lsQueueTable, self.loadBufferTable)
        MainWindow.setTabOrder(self.loadBufferTable, self.storeBufferTable)
        MainWindow.setTabOrder(self.storeBufferTable, self.regTable)
        MainWindow.setTabOrder(self.regTable, self.insTable)
        MainWindow.setTabOrder(self.insTable, self.rsTable)
        MainWindow.setTabOrder(self.rsTable, self.btnMemModify)
        MainWindow.setTabOrder(self.btnMemModify, self.memTable)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tumasulo算法演示平台", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Instructions:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Op", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Dest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Srcj", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Srck", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "发射", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "执行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.insTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "写回", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Resvervation Stations:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Add3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Mult1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Mult2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Op", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vj", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vk", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qj", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rsTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Load/Store Queue", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.lsQueueTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Load Buffer:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Load3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.loadBufferTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Store Buffer:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Store3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Busy", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.storeBufferTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClock.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "地址：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "值：", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMemModify.setText(QtGui.QApplication.translate("MainWindow", "修改内存", None, QtGui.QApplication.UnicodeUTF8))
        item = self.memTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Addr", None, QtGui.QApplication.UnicodeUTF8))
        item = self.memTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Qi", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "F0", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "F7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("MainWindow", "F9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.regTable.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("MainWindow", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "指令", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "执行", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actLoad.setText(QtGui.QApplication.translate("MainWindow", "载入文件", None, QtGui.QApplication.UnicodeUTF8))
        self.actEdit.setText(QtGui.QApplication.translate("MainWindow", "手动编辑", None, QtGui.QApplication.UnicodeUTF8))
        self.actStep.setText(QtGui.QApplication.translate("MainWindow", "单步执行", None, QtGui.QApplication.UnicodeUTF8))
        self.actStep.setToolTip(QtGui.QApplication.translate("MainWindow", "单步执行", None, QtGui.QApplication.UnicodeUTF8))
        self.actMultStep.setText(QtGui.QApplication.translate("MainWindow", "连续单步执行", None, QtGui.QApplication.UnicodeUTF8))
        self.actRun.setText(QtGui.QApplication.translate("MainWindow", "连续执行", None, QtGui.QApplication.UnicodeUTF8))
        self.actMem.setText(QtGui.QApplication.translate("MainWindow", "编辑器", None, QtGui.QApplication.UnicodeUTF8))
        self.actRestart.setText(QtGui.QApplication.translate("MainWindow", "重新开始", None, QtGui.QApplication.UnicodeUTF8))
        self.actRestart.setToolTip(QtGui.QApplication.translate("MainWindow", "重新开始", None, QtGui.QApplication.UnicodeUTF8))
        self.actPause.setText(QtGui.QApplication.translate("MainWindow", "暂停", None, QtGui.QApplication.UnicodeUTF8))
        self.actPause.setToolTip(QtGui.QApplication.translate("MainWindow", "暂停", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
